apiVersion: v1
kind: Service
metadata:
    name: "smk8scluster-6dd1"
    labels:
        app: "smk8scluster-6dd1"
spec:
    type: LoadBalancer
    ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "smk8scluster-6dd1"